name: Docker

on:
  push:
    branches:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-variant: [ 'apache', 'cli', 'fpm', 'supervisor', 'dev', 'oci', 'supervisor-oci' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push the images
        run: |
          VERSION=${{ matrix.image-variant }}
          PHP_SHORT_VERSION=8.3
          PHP_VERSION=8.3.8
          IMAGE_ID=${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}
          PLATFORMS="linux/amd64, linux/arm64"

          docker buildx build --platform $PLATFORMS --file $VERSION/Dockerfile --tag $IMAGE_ID:$VERSION --tag $IMAGE_ID:${VERSION}-$PHP_VERSION --tag $IMAGE_ID:${VERSION}-$PHP_SHORT_VERSION --push .

          if [ "$VERSION" == "fpm" ]; then 
            docker buildx build --platform $PLATFORMS --file $VERSION/Dockerfile --tag $IMAGE_ID:latest --push .
          fi